Quiz_project/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('quiz.urls') ),
    #path('' , include('result.urls') ),
    path('user/' , include('user.urls')),
    path('' , include('result.urls')),
    
]

quiz/urls.py
from django.urls import path
from quiz import views 
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    QuisListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,

    
)


urlpatterns = [
    # home url
    path('' , views.home , name= "home" ),
    # quizlist url
    path('quiz/' , QuisListView.as_view() , name= "main-view" ),
    # my created quizez url
    path('myquizes/' , views.myquizes , name= "myquizes"),
    # open quiz url
    path('quiz/<pk>/' , quiz_view , name="quiz-view"),
    # delete quiz url
    path('delete_quiz/<pk>/' , views.deleteQuiz ,name = "delete_quiz") ,
    # save result url (used by ajax)
    path('quiz/<pk>/save/' , save_quiz_view , name="save-view"),
    # view result of the quiz (used by ajax)
    path('quiz/<pk>/data/' , quiz_data_view , name="quiz-data-view"),
    # create quiz with it's questions 
    path('addquiz/' , views.addquiz , name= "addquiz" ),
    # path('addquestion/' , views.addquestion , name= "addquestion" ),
    # path('addAnswers/' , views.addAnswers , name= "addAnswers" ),
    # path('quizResult/' , views.quizResult , name= "quizResult" ),
   
    
    
]

user/urls.py
from django.contrib import auth
from django.urls import path
from django.contrib.auth import views as as_view ,views as auth_views
from user import views as user_views


urlpatterns = [
    # login url
    path('login/' , user_views.login_view ,name="login"),
    # logout url
    path('logout/' , user_views.logout_view , name= "logout"), 
    # signup url
    path('signup/' , user_views.signup_view ,name="signup"), 
    # profile url
    path('profile/' , user_views.profile_view ,name="profile"),
    # update url
    path('update/' , user_views.update_view ,name="update"),
    # change password url
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name="password_change.html" ),name='password_change'),
    # change password done url
    path('password_change/done',auth_views.PasswordChangeDoneView.as_view(template_name="password_change_done2.html"),name='password_change_done'),
    
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name,img,user_type="1",password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have an username')
        if not first_name:
            raise ValueError('Users must have a first name')
        if not last_name:
            raise ValueError('Users must have a last name')
        if not img:
            raise ValueError('Users must have a profile image')

        user = self.model(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            img=img,
            user_type=user_type,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password,first_name, last_name,img,user_type="0"):
        user = self.create_user(
            username=username,
            email=email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            img=img,
            user_type=user_type,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username        = models.CharField( verbose_name="username", max_length=30, unique=True)
    first_name        = models.CharField( verbose_name="first_name", max_length=30)
    last_name        = models.CharField( verbose_name="last_name", max_length=30)
    email           = models.EmailField(verbose_name="email", max_length=60, unique=True)
    img           = models.TextField(verbose_name="img")
    user_type        = models.CharField( verbose_name="user_type", max_length=2,default="1")

    date_joined     = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login      = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = [ 'email','first_name','last_name','img']

    objects = UserManager()

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from user.models import User


class RegistrationForm(UserCreationForm):
    username        = forms.CharField( max_length=20, help_text='Required. Add a valid username' )
    first_name        = forms.CharField(max_length=20, help_text='Required. Add a valid first name')
    last_name        = forms.CharField( max_length=20, help_text='Required. Add a valid last name')
    email           = forms.EmailField(max_length=60, help_text='Required. Add a valid email address')
    img           = forms.CharField(max_length=1000,help_text='Required. Add a valid profile imgae url')
    
    class Meta:
        model = User
        fields = ('username', 'first_name','last_name','email', 'img','password1', 'password2')


class UserAuthForm(forms.ModelForm):
    password = forms.CharField(label='Password' , widget=forms.PasswordInput)

    class Meta:
        model = User
        fields= ('username' , 'password')

    def clean(self):
        if self.is_valid():
            username= self.cleaned_data['username']
            password= self.cleaned_data['password']
            if not authenticate(username=username,password=password):
                raise forms.ValidationError("Invalid login")


     
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','email', 'img']

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate , logout
from user.forms import RegistrationForm, UserAuthForm, UserUpdateForm
from user.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# if it's get request it's will just load the page if it's post then
# it's will create new user record 
def signup_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
        else:
            context['registration_form'] = form
    else: #GET request
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'signup.html', context)

# if it's get request it's will just load the page if it's post then
# it's will check if the user entered username and pass
# is correct then it's will login if not then it's 
# will not login
def login_view(request):
    context = {}
    user =request.user
    if user.is_authenticated:
        messages.add_message(request,messages.SUCCESS,"loggined succseefuly ")
        return redirect('home')
    
    if request.POST:
        form =UserAuthForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate( username=username, password=password )

            if user:
                login(request, user)
                return redirect('home')

    else:
        form = UserAuthForm()
    
    context['login_form'] = form
    return render(request, 'login.html', context)

# get all user info and send it to profile
# page to presinte it to the user
def profile_view(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        context['profile'] = get_object_or_404(User, username=user)
        return render(request, 'profile.html', context)
    return redirect('login')

# this will logout if the user is logged in
@login_required(login_url='/user/login/')
def logout_view(request):
    logout(request)
    return redirect('home')

# this will open the open the update user data
# open the update page with the form 
@login_required(login_url='/user/login/')
def update_view(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        if u_form.is_valid():
            u_form.save()
            
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        context={'u_form': u_form}

    return render(request, 'update.html', context)

user/templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <style>
        label{
            color: rgb(187, 160, 110);
        }
    </style>

</head>


<div class="login">
<form method="post">
    <h1 style="margin-bottom: 20px;color: rgb(187, 160, 110);">Login</h1>
    {% csrf_token %}
    {% for field in login_form %}
        <p>
            {{field.label_tag}}
            {{field}}

            {% if field.help_text %}
                <small style="color: grey;">{{field.help_text}}</small>
            {% endif %}

            
        </p>
    {% endfor %}
    {% for error in field.errors %}
                <p style="color: red;">{{error}}</p>
            {% endfor %}
            
            {% if login_form.non_field_errors %}
                <div style="color: red;">
                    <p>{{ login_form.non_field_errors }}</p>
                </div>
            {% endif %}
            
    <button type="submit" class="btn btn-primary btn-block btn-large">Login</button>

</form>


{% endblock content %}

user/templates/password_change.html
{% extends "base.html" %}

{% block title %}Change you password{% endblock %}
{% load static %}

{% block content %}
<head>
 <style>
  label{
    color: rgb(187, 160, 110);
  }
  input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);

   

outline: none;
padding: 8px;

font-size: 13px;







-o-transition: box-shadow .5s ease;
-ms-transition: box-shadow .5s ease;
transition: box-shadow .5s ease; 
  }
  input{
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  #id_img {
      width: 100%;
  
    color: black;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  
  
  input[type=submit]:hover {
    background-color: #45a049;
    

    
  }
  li {
    color: rgb(187, 160, 110);
  }
  main {
    
    background: #092756;
background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
    padding: 20px; 
  }
  </style>
  


</head>
  
 






  
<div id="fom">
<form method='POST' enctype="multipart/form-data">
  {%csrf_token%}
  {{ form.as_p }}
  <div style="margin-top: 95px;"></div>
  <button type='submit' class="btn btn-primary btn-block btn-large" style="width: 90px;">Update</button>
  <section style="margin-top: 39px;"></section>
  
<div id="zad"><section style="background-color:#616161; height: 0px; margin-top: 220px;"></section></div>
</form>
</div>




<!-- <head>
  <link rel="stylesheet" href="{% static 'css/resetpassword.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


    

  
  
  
  
  

</head>


<div class="login"  id="bg">
<h1 style="color: rgb(187, 160, 110);">Change your password</h1>
  <div>
  <p>Use the form below to change your password.</p>
  <form action="." method="post" >
    {{ form.as_p }}
    <p><input type="submit" value="Change"  class="btn btn-primary btn-block btn-large"></p>
    {% csrf_token %}
  </form>
</div>

</div>
</div> -->

{% endblock %}

user/templates/password_change_done.html
{% extends "base.html" %}

{% block title %}Password changed{% endblock %}

{% block content %}

<style>
  label{
    color: rgb(187, 160, 110);
  }
  input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);

    /* 

outline: none;
padding: 8px;

font-size: 13px;







-o-transition: box-shadow .5s ease;
-ms-transition: box-shadow .5s ease;
transition: box-shadow .5s ease; */
  }
  input[type=email], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  #id_img {
      width: 100%;
  
    color: black;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  
  
  input[type=submit]:hover {
    background-color: #45a049;
  }
  li {
    color: rgb(187, 160, 110);
  }
  main {
    
    background: #092756;
background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
    padding: 20px; 
  }
  </style>
  <h1 style="color: rgb(187, 160, 110);">Password changed</h1>
  <p style="color: rgb(187, 160, 110);">Your password has been successfully changed.</p>
{% endblock %}

user/templates/password_change_done2.html
{% extends "base.html" %}

{% block title %}Password changed{% endblock %}

{% block content %}

<style>
  label{
    color: rgb(187, 160, 110);
  }
  input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);

    /* 

outline: none;
padding: 8px;

font-size: 13px;







-o-transition: box-shadow .5s ease;
-ms-transition: box-shadow .5s ease;
transition: box-shadow .5s ease; */
  }
  input[type=email], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  #id_img {
      width: 100%;
  
    color: black;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    background: rgba(0,0,0,0.3);
    border: none;
    color: #fff;
    text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0.3);
    box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
  }
  
  
  input[type=submit]:hover {
    background-color: #45a049;
  }
  li {
    color: rgb(187, 160, 110);
  }
  main {
    
    background: #092756;
background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
    padding: 20px; 
  }
  </style>
  <h1 style="color: rgb(187, 160, 110);">Password changed</h1>
  <p style="color: rgb(187, 160, 110);">Your password has been successfully changed.</p>
{% endblock %}

user/templates/resetpass.html
{% extends 'base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
  


{% endblock %}