Quiz_project/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('quiz.urls') ),
    #path('' , include('result.urls') ),
    path('user/' , include('user.urls')),
    path('' , include('result.urls')),
    
]

quiz/urls.py
from django.urls import path
from quiz import views 
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    QuisListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,

    
)


urlpatterns = [
    # home url
    path('' , views.home , name= "home" ),
    # quizlist url
    path('quiz/' , QuisListView.as_view() , name= "main-view" ),
    # my created quizez url
    path('myquizes/' , views.myquizes , name= "myquizes"),
    # open quiz url
    path('quiz/<pk>/' , quiz_view , name="quiz-view"),
    # delete quiz url
    path('delete_quiz/<pk>/' , views.deleteQuiz ,name = "delete_quiz") ,
    # save result url (used by ajax)
    path('quiz/<pk>/save/' , save_quiz_view , name="save-view"),
    # view result of the quiz (used by ajax)
    path('quiz/<pk>/data/' , quiz_data_view , name="quiz-data-view"),
    # create quiz with it's questions 
    path('addquiz/' , views.addquiz , name= "addquiz" ),
    # path('addquestion/' , views.addquestion , name= "addquestion" ),
    # path('addAnswers/' , views.addAnswers , name= "addAnswers" ),
    # path('quizResult/' , views.quizResult , name= "quizResult" ),
   
    
    
]

result/urls.py
from django.urls import path
from quiz import views 
from django.conf.urls.static import static
from django.conf import settings
from .views import (

    results_view,
    
)

urlpatterns = [

    path('result/<id>' , results_view , name="results_view"),

    
]

quiz/models.py
from django.db import models
import random 
from user.models import User
from datetime import datetime
# Create your models here.
DIFF_CHOICES =(
    ('easy','easy'),
    ('medium','medium'),
    ('hard','hard'),
)

class Quiz (models.Model):
    
    name =models.CharField(max_length=150,null=False)
    number_of_question =models.IntegerField(null=False)
    time=models.IntegerField(null=False)
    score_to_pass=models.IntegerField(null=False)
    difficulty=models.CharField(null=False,max_length=15,choices=DIFF_CHOICES)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz_type= models.BooleanField(default=True)
    date = models.DateField(null=True , default=datetime.now)


    def __str__(self):
        return f"{self.name}"

    def get_questions(self):
        questions= list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_question]
        
    class Meta:
        verbose_name_plural = 'Quizes'

result/models.py
from django.db import models
from quiz.models import Quiz
from user.models import User
from datetime import datetime


# Create your models here.

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    date = models.DateField(null=True , default=datetime.now)

    def __str__(self):
        return str(self.pk)+ "-" + str(self.score)

quiz/views.py
from django.shortcuts import render , HttpResponse , redirect
from django.http import JsonResponse
from datetime import datetime
from .models import Quiz
from django.views.generic import ListView
from question.models import Answer, Question
from result.models import Result
from quiz.models import Quiz
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return  render(request,'home.html' , {}) 

#show all quizes
class QuisListView(ListView):
    model=Quiz
    template_name='quiz/quizlist.html'


@login_required(login_url='/user/login/')
#show quizes that user create
def myquizes(request): 
    user=request.user
    myQui = Quiz.objects.filter(created_by=user)
    return render(request , 'quiz/myquizes.html' , 
    {"ob" : myQui  })

#start quiz
@login_required(login_url='/user/login/')
def quiz_view(request , pk):
    
    quiz=Quiz.objects.get(pk=pk)
    counter = Result.objects.filter(quiz=pk,user=request.user.id).count()
    #result=Result.objects.get(pk=pk)
    print(quiz.quiz_type)
    if quiz.quiz_type==True:
        return render(request , 'quiz/startQuiz.html' ,
        {   
        "obj" : quiz
        } )
    elif  quiz.quiz_type==False:
        if counter > 0 :
            result = Result.objects.get(quiz=pk,user=request.user.id)
            return render(request , 'quiz/private.html' ,
            {   
                "obj" : quiz,
                "resutl":result,
            } )
        else:
            return render(request , 'quiz/startQuiz.html' ,
        {   
        "obj" : quiz
        } )
        
@login_required(login_url='/user/login/')
def quiz_data_view (request ,pk):
    questions =[]
    for q in quiz.get_questions():
        answers=[]
        for a in q.get_answers():
            answers.append(a.text)
            # print(a.text)
        # print("q.get_answers")
        # print(answers)
        questions.append({str(q):answers})
    return JsonResponse({
        'data' : questions,
        'time' : quiz.time,
    })
    
# this view for sending data 
@login_required(login_url='/user/login/')
def quiz_data_view (request ,pk):
    quiz=Quiz.objects.get(pk=pk)
    questions =[]
    for q in quiz.get_questions():
        answers=[]
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q):answers})
    return JsonResponse({
        'data' : questions,
        'time' : quiz.time,
    })


 #save students answers   

@login_required(login_url='/user/login/')
def save_quiz_view(request,pk):
    #print(request.POST)
    if request.is_ajax():
        questions=[]
        data=request.POST
        data_=dict(data.lists())
        #print(type(data))
        #print(type(data_))
        data_.pop('csrfmiddlewaretoken')
        for k in data_.keys():
            print('key: ', k)
            question=Question.objects.get(text=k)
            questions.append(question)
        print(questions)
        user=request.user
        quiz=Quiz.objects.get(pk=pk)
        score = 0
        multipler = 100/ quiz.number_of_question
        results =[]
        correct_answer= None 
        for q in questions:
            a_selected =request.POST.get(q.text)
            if a_selected !="":
                question_answers=Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected== a.text:
                        if a.correct:
                            score +=1
                            correct_answer= a.text
                    else:
                        if a.correct:
                            correct_answer=a.text
                results.append({str(q):{'correct_answer': correct_answer, 'answered': a_selected }})
            else:
                results.append({str(q):'Not answered'})
        score_ =score * multipler 
        print("the count of the ruselt :")
        # print(Result.objects.filter(quiz=quiz.id,user=user.id).count())
        if Result.objects.filter(quiz=quiz.id,user=user.id).count() > 0:
            print('there is user')
            Result.objects.filter(quiz=quiz.id,user=user.id).delete()
            print("old score is deleted")
            Result.objects.create(quiz=quiz,user=user,score=score_)
            print("the score is replaced")
        else:
            print('there is no old score')
            Result.objects.create(quiz=quiz,user=user,score=score_)
        if score_ >= quiz.score_to_pass:
            return JsonResponse({'passed':True,'score':score_ ,'results': results})
        else:
            return JsonResponse({'passed': False ,'score':score_ ,'results': results})


#delete quiz
@login_required(login_url='/user/login/')
def deleteQuiz(request , pk):
    quiz=Quiz.objects.get(id=pk)
    quiz.delete()
    context= {'item':quiz}
    messages.add_message(request,messages.SUCCESS,"quiz deleted ")
    return redirect('/myquizes' )


# /////////////////////////////////////////////////

# data will come form the fron-end with this format
# ['q-1$$TorF - 1+1=2', 'q-1-answer - true', 
# 'q-2$$MCQ - 1+2', 'q-2-answer - 3', 'ch-2 ### q-2 - 4',
#  'ch-3 ### q-2 - 2']

# answer : q-2-answer = 3
# choicess : ### q-2 = 2 ,
# solit by $$ for Question type
# split by  ###  for choice 
# split by answer -  for answer of Question
# split by  -  for the value

# this will convert the POST to array of dictionary
# dictionary = {
# item: this will store the name of the tag element
# value : this will store the value of the tag element
# flag : alwayz false , this if it's has been added to data base
# }
def convertToArr(obj):
    dele=["csrfmiddlewaretoken","name","time","ispublic","difficulty","type"]
    arr=[]
    for item in obj:
        # print(item)
        if item not in dele:
            el={
                "item":item,
                "value":obj[item],
                "flag":False,
                }
            arr.append(el)
    return arr

# this method will check if the element is question then it's will return true
def isQuestion(item):
    if "$$" in item:
        print("this is question")
        return True
    return False

# this method will check if the element is choice then it's will return true
def isChoice(item):
    if " ### " in item:
        print("this is Choice")
        return True
    return False

# you will give this method the question name 
# and it's will return the answer of the this question 
# if it's available
def retAnswer(arr,q,flag=True):
    # search for answer of this question
    ttt=""
    if q != -1:
        ttt= q+"-answer"
        print(ttt)
    for el in arr:
        if ttt in el["item"]:
            print(el)
            if el["value"] != -1:
                val = el["value"]
                print(val)
                if flag:
                    el["flag"]=True
                    
                return val

    return -1

# this method will check if the element is choice and return it's value
def returnChoice(el,question):

    if isChoice(el["item"]):
            if el["item"] != -1:
                q=el["item"].split(" ### ")
                if q[1] == question:
                    if el["value"] != -1:
                        return el["value"]
                        
    return -1

# this will use all the above method to create the query for this quiz
# and return array of query 
def covertStrToQueries(arr):
    arrOfQ=[]
    i=-1
    for element in arr:
        i+=1
        print("--------------------")
        print("itiration number :"+str(i))
        query=""
        question=""
        answer=""
        print("arr before Question: ")
        print(arr)
        print("item : "+element["item"])
        if isQuestion(element["item"]) and element["flag"] == False:
            if element["value"] != -1:
                ttr = element["item"]
                tt = ttr.split("$$")
                query+=tt[1]+","+element["value"]+","
                question=tt[0]
                element["flag"]=True

            print("question is :"+question)
            print("the answer is :")
            print("arr before answer: ")
            print(arr)
            if retAnswer(arr,question,False) != -1:
                answer=str(retAnswer(arr,question))
                query+=answer+","
                print(answer)
                
            
            # print(arr)

            print("the choicess is :")
            print("arr before choicess: ")
            print(arr)
            for el in arr:
                print(returnChoice(el,question))
                if returnChoice(el,question) != -1 and el["flag"]== False:
                    choice=str(returnChoice(el,question))
                    query+=choice+","
                    print(choice)
                    el["flag"]=True
        if query != "":
            arrOfQ.append(query)
            

    print("print the array :")
    print(arr)
    print("print the query :")
    print(arrOfQ)
    return arrOfQ

# if it's get request it's will load the page
# if it's post then it's will get the quiz and it's questions 
# and choices and convert them to queries then add them 
# to the data base under one quiz record

@login_required(login_url='/user/login/')
def addquiz(request):
    # request.POST["name"]
    name= ""
    time= ""
    passScore= ""
    dif= ""
    public= ""
    quiz=""
    queries=""
    requierd=["name","time","passScore","difficulty"]
    missing=False

    if not request.POST:
        return  render(request,'quiz/newquiz.html' , {}) 
    else:
        print("POST")
        for item in requierd:
            if item not in requierd:
                missing=True
        if not missing:
            obj=request.POST
            name = obj["name"]
            time = obj["time"]
            passScore = obj["passScore"]
            dif = obj["difficulty"]
        else : 
            HttpResponse("erorr in post data")
        arr =convertToArr(obj)
        print(arr)

result/views.py
from django.shortcuts import render , HttpResponse , redirect
from django.http import JsonResponse
from django.views.generic import ListView
from question.models import Answer, Question
from result.models import Result

# Create your views here.



#class QuisListView(ListView):
#    model=Result
#    template_name='quiz/results.html'


#shows results
def results_view(request,id):
 
    print(id+"id")
    result=Result.objects.all().filter(quiz=id)

    print(result)

    return render(request , 'quizresult.html' ,
    {   
    "results" : result
    } )

quiz/templates/quiz/addQuiz.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/startquiz.css' %}">
</head>

<div class="container content mt-3">
    <h3>add quiz</h3>

    <form>
        <label >Question 1</label>




    </form>
<!-- end of row ms-1 -->

</div> <!-- end of container -->

<div style="color: white;">
    s
</div>

{% endblock  %}

quiz/templates/quiz/addquiz.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
   
</head>


<div style="margin-top: -20;"></div>
<div class="container content mt-3" ></div>


    <div class="row">
        <div class="col-md-8 name">
            <h3>Add quiz</h3>
        </div>

    </div>

    <div class="row ms-1">

     


        <!----------start------------>

        <div id="content" class="colM">

  

            <div id="content-main">



                <form method="post" id="quiz_form" novalidate=""><input type="hidden" name="csrfmiddlewaretoken"
                        value="">
                    <div>







                        <fieldset class="module aligned ">



                            <div class="form-row field-name">


                                <div>


                                    <label class="required" for="id_name">Name:</label>

                                    <input type="text" name="name" class="vTextField" maxlength="150" required
                                        id="id_name">



                                </div>

                            </div>

                            <div class="form-row field-number_of_question">


                                <div>


                                    <label class="required" for="id_number_of_question">Number of question:</label>

                                    <input type="number" name="number_of_question" class="vIntegerField" required=""
                                        id="id_number_of_question">



                                </div>

                            </div>

                            <div class="form-row field-time">


                                <div>


                                    <label class="required" for="id_time">Time:</label>

                                    <input type="number" name="time" class="vIntegerField" required="" id="id_time">



                                </div>

                            </div>

                            <div class="form-row field-score_to_pass">


                                <div>


                                    <label class="required" for="id_score_to_pass">Score to pass:</label>

                                    <input type="number" name="score_to_pass" class="vIntegerField" required=""
                                        id="id_score_to_pass">



                                </div>

                            </div>

                            <div class="form-row field-difficulty">


                                <div>


                                    <label class="required" for="id_difficulty">Difficulty:</label>

                                    <select name="difficulty" required="" id="id_difficulty">
                                        <option value="" selected="">---------</option>

                                        <option value="easy">easy</option>

                                        <option value="medium">medium</option>

                                        <option value="hard">hard</option>

                                    </select>



                                </div>

                            </div>

                        </fieldset>

                    </div>
                </form>
            </div>


            <br class="clear">
        </div>

        <!-----------end----------->
        <div class="col-xs-12">

            <div class="row">
                <div class="col-xs-12 col-med-6 mg-lf">





                </div>
            </div><!-- end of row -->
        </div><!-- end of add quiz  -->
        <hr class="border-b">
        <div class="col-xs-12 qustion">
            <button type="button" class="btn btn-light float-end">Submit</button>
        </div>
    </div><!-- end of row ms-1 -->
<div style="margin-top: 5px;"></div>
</div> <!-- end of container -->






{% endblock %}

quiz/templates/quiz/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<p>Are you sure you want to delete {{item}} quiz?</p>
<form method="POST">
<a href="{% url'home' %}">Cancel</a>
<input type="submit" name="Confirm">
</form>
{% endblock  %}

quiz/templates/quiz/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <link rel="stylesheet" href="{% static 'css/quizlist.css' %}">
</head>

<div class="container contai">
    
    <!-- button row-->


  


    <div class="row mt-1">
        <div class="col-12 col-md-6 col-xl-4 mx-auto text-center">
            <div class="btn-group mb-5 flex-wrap button-group
             filter-button-group" role="group">
  
             <button type="button" class="btn btn-classified" data-filter="*">All</button>
             <button type="button" class="btn btn-classified" data-filter=".hard">easy</button>
             <button type="button" class="btn btn-classified" data-filter=".mid">Meduim</button>
             <button type="button" class="btn btn-classified" data-filter=".easy">Hard</button>
             
            </div>
        </div>
      </div>
    <!-- end button row-->
    <div class="row grid mt-2 text-center mx-auto" >


        <!-- start of quiz -->
       

        {% block container %}
        1111
        {{obj.name }}
        {% endblock container %}

        <!-- end of quiz -->


        <!-- start of quiz -->
        <div class="col-12  col-xs-6 col-md-4 col-xl-3 mt-2 manga" >
            <div class="card"  >
                <div class="card-body">
                  <h5 class="card-title">Quiz title</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Created by</h6>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <h6 class="card-subtitle mb-2  " id="easy">Hard</h6>
                  <!-- <a href="#" class="card-link">Start Quiz</a> -->
                </div>
                <a class="none-link" href="http://google.com"><div class="btnn">Start Quiz</div></a>
              </div>
        </div>
        <!-- end of quiz -->
        
        <!-- start of quiz -->
        <div class="col-12  col-xs-6 col-md-4 col-xl-3 mt-2 manga" >
            <div class="card"  >
                <div class="card-body">
                  <h5 class="card-title">Quiz title</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Created by</h6>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <h6 class="card-subtitle mb-2  " id="easy">Hard</h6>
                  <!-- <a href="#" class="card-link">Start Quiz</a> -->
                </div>
                <a class="none-link" href="http://google.com"><div class="btnn">Start Quiz</div></a>
                
              </div>
        </div>
        <!-- end of quiz -->

                <!-- start of quiz -->
                <div class="col-12  col-xs-6 col-md-4 col-xl-3 mt-2 manga" >
                    <div class="card"  >
                        <div class="card-body">
                          <h5 class="card-title">Quiz title</h5>
                          <h6 class="card-subtitle mb-2 text-muted">Created by</h6>
                          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <h6 class="card-subtitle mb-2  " id="easy">Hard</h6>
                          <!-- <a href="#" class="card-link">Start Quiz</a> -->
                        </div>
                        <a class="none-link" href="http://google.com"><div class="btnn">Start Quiz</div></a>
                        
                      </div>
                </div>
                <!-- end of quiz -->

                        <!-- start of quiz -->
        <div class="col-12  col-xs-6 col-md-4 col-xl-3 mt-2 manga" >
            <div class="card"  >
                <div class="card-body">
                  <h5 class="card-title">Quiz title</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Created by</h6>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <h6 class="card-subtitle mb-2  " id="easy">Hard</h6>
                  <!-- <a href="#" class="card-link">Start Quiz</a> -->
                </div>
                <a class="none-link" href="http://google.com"><div class="btnn">Start Quiz</div></a>
                
              </div>
        </div>
        <!-- end of quiz -->


                <!-- start of quiz -->
                <div class="col-12  col-xs-6 col-md-4 col-xl-3 mt-2 manga" >
                    <div class="card"  >
                        <div class="card-body">
                          <h5 class="card-title">Quiz title</h5>
                          <h6 class="card-subtitle mb-2 text-muted">Created by</h6>
                          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                          <h6 class="card-subtitle mb-2  " id="easy">Hard</h6>
                          <!-- <a href="#" class="card-link">Start Quiz</a> -->
                        </div>
                        <a class="none-link" href="http://google.com"><div class="btnn">Start Quiz</div></a>
                        
                      </div>
                </div>
                <!-- end of quiz -->

                
                
        

    </div>  
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script src="{% static 'js/filter.js' %}"></script>

{% endblock  %}

quiz/templates/quiz/myquizes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<head>
 
  <link rel="stylesheet" href="{% static 'css/myquizez.css' %}">
</head>

<div class="container contai">
    
    <!-- button row-->
    <div class="row mt-1">
        <div class="col-12 col-md-6 col-xl-4 mx-auto text-center">
<br><br>
        </div>
      </div>
    <!-- end button row-->
    <div class="row grid mt-2 text-center mx-auto" >
        
     
        <!-- start of quiz -->
        
        
       


      


       
      <!-- end of quiz -->
     
     

      {% for myquiz in  ob %}
      
<!-- start of quiz -->
<div class="col-12  col-xs-6 col-md-4 col-xl-3 mt-2 manga" >
  <form method="POST" action="">
    <div class="card"  >
      
        <div class="card-body">
          
          <h5 class="card-title">Quiz Name: {{myquiz.name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{myquiz.user}}</h6>
          <p class="card-text">  Number of questions: {{myquiz.number_of_question}}</p>
          <p class="card-text">  Duration: {{myquiz.time}} min</p>
          <p class="card-text">  Score To Pass: {{myquiz.score_to_pass}} % </p>
          <h6 class="card-subtitle mb-2  " id="easy">{{myquiz.difficulty}}</h6>
          
          <!-- <a href="#" class="card-link">Start Quiz</a> -->
        </div>
        
      </div>
      <div class="card-footer text-muted">
        <!-- <a type="button" class="btnn btn-outline-success m-1 p-1">Update</a> -->
        <a type="button" class="btnn btn-outline-danger m-1 p-1"  href="{% url 'delete_quiz' pk=myquiz.id%}"> delete </a>

        <a type="button" class="btnn btn-outline-warning m-1 p-1" href="{% url 'results_view' id=myquiz.id %}" >Result</a>
        
        
    </div>
    </form>
</div>
<!-- end of quiz -->
{%endfor%}

    </div>  
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>



{% endblock  %}

quiz/templates/quiz/newquiz.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/newquiz.css' %}">
</head>

<div class="container content mt-5">
    <form id="addQuizForm" method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="">
        
        <div class="row borderr">
            <label for="">Quiz name</label>
            <input type="text" name="name" required placeholder="Calculas">
        </div>

        <div class="row borderr">
            <label for="">Time</label>
            <input type="number" min="1" name="time" required placeholder="20">
        </div>
        <div class="row borderr">
            <label for="">Score To Pass</label>
            <input type="number" min="5" step="5" name="passScore" required placeholder="60">
        </div>
        <div class="row borderr">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="ispublic" name="ispublic" value="public">
                <label class="form-check-label" for="inlineCheckbox1">Privte</label>
            </div>

        </div>

        <div class="row borderr">
            <label for="">difficulty</label>
            <select name="difficulty" >
                <option value="easy">Easy</option>
                <option value="medium">Medium</option>
                <option value="hard">Hard</option>
            </select>
        </div>

        <div id="add" class="row borderr">
            <label for="">add quistion</label>
            <select name="type" id="selectType">
                <option value="true">true or false</option>
                <option value="false">MCQ</option>
            </select>
            <button onclick="addQuestion()" class="btnn" id="addqu" type="button">Add Quistion</button>
        </div>
        <div id="submit" class="row">
            <button class="btnn" type="submit">Add Quiz</button>
        </div>
    </form>
</div>

<div style="color: white;">
    s
</div>


<script src="{% static 'js/addquistion.js' %}"></script>

{% endblock %}

quiz/templates/quiz/private.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
  <link rel="stylesheet" href="{% static 'css/startquiz1.css' %}">
</head>


<!-- Center columns in a Row -->
<div class="row d-flex justify-content-center text-center">
  <div class="col-4">
    
  </div>
  <div class="col-4 pt-5">
    <h5 class="card-title" style="color: seashell;">You already submitted {{obj.name}} quiz</h5>
  
    <h6 class="card-subtitle mb-2  " id="easy" style="color: seashell;">Your result is :{{resutl.score}}</h6>
    
  </div>
  <div class="col-4">
   
  </div>
</div>

  
</div>
</div>
</div>



{% endblock  %}

quiz/templates/quiz/quizlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<head>
  <link rel="stylesheet" href="{% static 'css/quizlist.css' %}">
</head>

<div id="baaack">
  <div id="baaack">
    <div class="container contai">

      <!-- button row-->
      <div class="row mt-1">
        <div class="col-12 col-md-6 col-xl-4 mx-auto mt-2 text-center">
          <div class="btn-group mb-5 flex-wrap button-group
            filter-button-group" role="group">

            <button type="button" class="btn btn-classified" data-filter="*">All</button>
            <button type="button" class="btn btn-classified"
              data-filter=".hard">Hard</button>
            <button type="button" class="btn btn-classified"
              data-filter=".medium">Meduim</button>
            <button type="button" class="btn btn-classified"
              data-filter=".easy">Easy</button>

          </div>
        </div>
      </div>
      <!-- end button row-->
      <div class="row grid mt-2">

        {% for obj in object_list %}

        {% if obj.quiz_type %}
        <!-- start of quiz -->
        <div class="col-xs-12 text-center col-md-6 col-xl-3 mt-2 {{obj.difficulty}}" >

          <div class="card" style="background-color: white;">
            <div class="card-body">
              <h5 class="card-title">Quiz Name: {{obj.name}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{obj.user}}</h6>
              <p class="card-text"> Number of questions:
                {{obj.number_of_question}}</p>
              <p class="card-text"> Duration: {{obj.time}} min</p>
              <p class="card-text"> Score To Pass: {{obj.score_to_pass}} %</p>
              <p class="card-text"> Created By: {{obj.created_by}} </p>
              <h6 class="card-subtitle mb-2"id="easy">{{obj.difficulty}}</h6>
              <!-- <a href="#" class="card-link">Start Quiz</a> -->
            </div>
          </div>
          <div class="card-footer text-muted">
            <button class="btnn btn-link modal-button btnn btn-outline-success
              m-1 p-1"
              onclick="const url=window.location.href
              const modalBtns=
              [...document.getElementsByClassName('modal-button')]
              modalBtns.forEach(modalBtn=>
              modalBtn.addEventListener('click',()=>{
              const pk=modalBtn.getAttribute('data-pk')
              window.location.href=url+pk
              }))
              "
              data-pk="{{obj.pk}}"
              data-togglr="modal"
              data-target="#quizStartModal"

              style="text-decoration: none;">Start Quiz</button>
          </div>
        </div>
        {%endif%}
        {% endfor %}

      </div>
      <!-- end of quiz -->


    </div>
  </div>
</div>

<script src="{% static 'js/iso.js' %}"></script>
<script src="{% static 'js/filter.js' %}"></script>
{% endblock %}